[package]
name = "mediant-rs"
version = "0.1.0"
edition = "2021"
description = "Approximate real numbers as fractions using the Stern-Brocot tree"

[dependencies]
bpaf = { version = "0.9", features = ["derive"] }
